# Generated by Django 5.2 on 2025-05-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_city_remove_profile_governorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(default='home', max_length=100),
        ),
    ]
