# Generated by Django 5.2 on 2025-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.CharField(default='Apartment', max_length=100),
        ),
    ]
