# Generated by Django 5.2 on 2025-05-10 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_address_address_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('damaged', 'Damaged Product'), ('defective', 'Defective/Not Working'), ('wrong', 'Wrong Item Received'), ('missing', 'Missing Parts/Accessories'), ('quality', 'Poor Quality'), ('description', "Doesn't Match Description"), ('other', 'Other Issue')], max_length=100)),
                ('order_number', models.CharField()),
                ('product_name', models.CharField()),
                ('product_image', models.ImageField(default='default_product.png', upload_to='product_images/')),
                ('complaint_description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField()),
                ('issue_description', models.TextField()),
                ('issue_image', models.ImageField(default='default_issue.png', upload_to='issue_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
