# Generated by Django 5.2 on 2025-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_productcomplaint_technicalcomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomplaint',
            name='order_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productcomplaint',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='technicalcomplaint',
            name='page_url',
            field=models.CharField(max_length=255),
        ),
    ]
