# Generated by Django 5.2 on 2025-04-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
