# Generated by Django 5.2 on 2025-05-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=list),
        ),
    ]
