# Generated by Django 5.2 on 2025-05-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price_without_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
