# Generated by Django 5.2 on 2025-05-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_order_price_without_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
