# Generated by Django 5.2 on 2025-05-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_updated_at_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
    ]
